
CREATE TABLE  IF NOT EXISTS CURRENCY_RATE (
	currency VARCHAR(10)NOT NULL PRIMARY KEY,
    rate decimal(10,4) NOT NULL ,
    currency_name VARCHAR(50)NOT NULL ,
    memo text NOT NULL ,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(30) NOT NULL  ,
    update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    update_by VARCHAR(30) NOT NULL  
);

